remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Site settings
title: "Kasper Brandenburg"
description: "Knowledge Base & Security Research"
url: "https://www.kasperbrandenburg.dk"

# Just the Docs theme settings  
search_enabled: true

# Navigation structure
nav_sort: case_insensitive

# Footer settings
footer_content: "Copyright &copy; 2025 Kasper Brandenburg."

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/kasperbrandenburg/kasperbrandenburg.github.io"

# Makes Aux links open in a new tab
aux_links_new_tab: true